language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm install -g ionic cordova

script:
  - ionic cordova platform rm browser --save
  - ionic cordova platform add browser@latest --save
  - ionic cordova build browser --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: www

